### ISSUE TITLE
[question] Logging inputs without OJD

### ISSUE THREAD

**Issue by INobody95** [NicholeMattera/OJDS-NX#3]
Hello Nichole,
I'm coming from Anthony Materras (related?) OJD-GitHub (https://github.com/KernelZechs/open-joystick-display/issues/44).

In short:
To create a free (well not free, since you'd need a arduino) alternative to things like the switch up game enhancer (not available in europe, and pricejacked in the states) it would be unbelievable helpful to be able to log real gameplay inputs on the switch. With those logs it would be a lot easier to create all kind of macros which can be run on Arduinos using LUFA (Pro Controller emulation). 

I read the files in the source folder, but cant fully wrap my mind around everything. Got rudimentary c/c++ (2 semesters in university, prof wrote code on overhead projector lol) and python (selftaught, googling whatever i need, for bachelorthesis on which I'm working right now) understanding. 

From what I'm understanding I'd have to run OJDS-NX and sys-ftpd on my cfw switch, then connect to the switch (for example via Filezilla). 
In python (but should be possible in c++ aswell) I'd create a socket and connect to the Switches IP and port.

_Once connected I dont know how to send a poll request to OJDS-NX and which format (simple string, list, whatever) the response(s) would be._

Knowing the above two things I'd match the system (PC) time to the response(s). That way I can calc the delay between button presses later. 
A simple inifite loop (broken by press of capture button on switch) would allow me to record the inputs.

I'd like to kindly request your help for my endeavor. Did you may have something like that while developing OJDS-NX?

Best regards

**Comment by NicholeMattera** [comment]
I just wrote this real quick; I think this might suffice for what you are looking for: https://github.com/NicholeMattera/Controller-Poller

**Comment by INobody95** [comment]
Oh, wow thank you. I will try it after work.

**Comment by INobody95** [comment]
After taking 2 hours to install jansson on my Pi, I’m stuck with not being able to get the switch connected to a local (offline) network. 
I don’t want to get it banned, despite being my offline switch. 
Do you know if it’s possible to do, or do I need Internet for this?

**Comment by NicholeMattera** [comment]
You can use 90DNS to be able to go online and block all network traffic to Nintendo.

**Comment by INobody95** [comment]
Sorry to bother you again. Got 90DNS set up, established a connection with sys-ftpd light and FIlezilla, but cant get it to work. Tried the following with and without Filezilla connected:
#####
root@raspberrypi:/media/pi/E5FC-761B/Controller-Poller-master# ./ctrl_poller 192.168.1.6 > inputs.csv
**bash: ./ctrl_poller: Permission denied**
root@raspberrypi:/media/pi/E5FC-761B/Controller-Poller-master# bash ./ctrl_poller 192.168.1.6 > inputs.csv
**./ctrl_poller: ./ctrl_poller: cannot execute binary file**
root@raspberrypi:/media/pi/E5FC-761B/Controller-Poller-master# chmod +x ./ctrl_poller 192.168.1.6 > inputs.csv
**chmod: cannot access '192.168.1.6': No such file or directory**
#####
Any idea what could be wrong?

**Comment by INobody95** [comment]
Figured it out. Deleted the ctrl_poller file and used "make" again. Now its working perfectly. Will looking into making scripts to "translate the polls into triggers" as soon as I got more time.

**Comment by INobody95** [comment]
Addition: Localmode like Pokemon Sw/Sh seems to break the connection and won’t work. I was able to reconnect afterwards with FileZilla, but not with controller poller. Maybe have to off and on the ojdsns module in Kosmos settings
